[versions]
googleJavaFormat = "1.23.0"
kotlin = "2.0.0"

# plugins
gradlePlugin-intelliJPlatform = "2.0.0"
gradlePlugin-spotless = "6.25.0"

[libraries]
googleJavaFormat = { module = "com.google.googlejavaformat:google-java-format", version.ref = "googleJavaFormat" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "gradlePlugin-intelliJPlatform" }
spotless = { id = "com.diffplug.spotless", version.ref = "gradlePlugin-spotless" }
