[versions]
java = "17"
kotlin = "2.2.0"
com-amazonaws-aws-lambda-java-core = "1.2.1"
com-amazonaws-aws-lambda-java-events = "2.2.9"
com-google-code-gson-gson = "2.10.1"
com-google-googlejavaformat-google-java-format = "1.23.0"
com-google-guava-guava = "33.5.0-jre"
com-google-truth-truth = "1.0"
org-graalvm = "25.0.1"
graalvmPlugin = "0.11.1"
junit-junit = "4.13.1"
org-jline = "3.30.6"
net-java-dev-jna-jna = "4.2.2"
org-ec4j-core = "1.2.0"

# plugins
gradlePlugin-dokka = "2.0.0"
gradlePlugin-intelliJPlatform = "2.6.0"
gradlePlugin-ktfmt = "0.24.0"
gradlePlugin-nexusPublish = "2.0.0"
gradlePlugin-shadowJar = "9.0.2"

[libraries]
amazon-aws-lambda-core = { module = "com.amazonaws:aws-lambda-java-core", version.ref = "com-amazonaws-aws-lambda-java-core" }
amazon-aws-lambda-events = { module = "com.amazonaws:aws-lambda-java-events", version.ref = "com-amazonaws-aws-lambda-java-events" }
amazon-aws-sdk-bom = { module = "software.amazon.awssdk:bom", version = "2.10.73" }
amazon-aws-sdk-lambda = { module = "software.amazon.awssdk:lambda" }
ec4j = { module = "org.ec4j.core:ec4j-core", version.ref = "org-ec4j-core" }
googleJavaformat = { module = "com.google.googlejavaformat:google-java-format", version.ref = "com-google-googlejavaformat-google-java-format" }
googleTruth = { module = "com.google.truth:truth", version.ref = "com-google-truth-truth" }
gson = { module = "com.google.code.gson:gson", version.ref = "com-google-code-gson-gson" }
graalvm-nativeimage = { module = "org.graalvm.nativeimage:svm", version.ref ="org-graalvm" }
guava = { module = "com.google.guava:guava", version.ref = "com-google-guava-guava" }
jline-terminal = { module = "org.jline:jline-terminal", version.ref = "org-jline" }
jline-terminal-jansi = { module = "org.jline:jline-terminal-jansi", version.ref = "org-jline" }
jline-terminal-jna = { module = "org.jline:jline-terminal-jna", version.ref = "org-jline" }
jline-terminal-jni = { module = "org.jline:jline-terminal-jni", version.ref = "org-jline" }
junit = { module = "junit:junit", version.ref = "junit-junit" }
jna = { module = "net.java.dev.jna:jna", version.ref = "net-java-dev-jna-jna" }
ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
kotlin-compilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit4 = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "gradlePlugin-dokka" }
graalvm = { id = "org.graalvm.buildtools.native", version.ref = "graalvmPlugin" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "gradlePlugin-intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "gradlePlugin-ktfmt" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradlePlugin-nexusPublish" }
shadowJar = { id = "com.gradleup.shadow", version.ref = "gradlePlugin-shadowJar" }
