[versions]
java = "17"
kotlin = "2.2.0-Beta2"
com-amazonaws-aws-lambda-java-core = "1.2.1"
com-amazonaws-aws-lambda-java-events = "2.2.9"
com-google-googlejavaformat-google-java-format = "1.23.0"
com-google-guava-guava = "32.0.0-jre"
com-google-truth-truth = "1.0"
junit-junit = "4.13.1"
net-java-dev-jna-jna = "4.2.2"
com-google-code-gson-gson = "2.10.1"

# plugins
gradlePlugin-dokka = "2.0.0"
gradlePlugin-intelliJPlatform = "2.6.0"
gradlePlugin-ktfmt = "0.22.0"
gradlePlugin-nexusPublish = "2.0.0"
gradlePlugin-shadowJar = "9.0.0-beta13"

[libraries]
amazon-aws-lambda-core = { module = "com.amazonaws:aws-lambda-java-core", version.ref = "com-amazonaws-aws-lambda-java-core" }
amazon-aws-lambda-events = { module = "com.amazonaws:aws-lambda-java-events", version.ref = "com-amazonaws-aws-lambda-java-events" }
amazon-aws-sdk-bom = { module = "software.amazon.awssdk:bom", version = "2.10.73" }
amazon-aws-sdk-lambda = { module = "software.amazon.awssdk:lambda" }
googleJavaformat = { module = "com.google.googlejavaformat:google-java-format", version.ref = "com-google-googlejavaformat-google-java-format" }
googleTruth = { module = "com.google.truth:truth", version.ref = "com-google-truth-truth" }
gson = { module = "com.google.code.gson:gson", version.ref = "com-google-code-gson-gson" }
guava = { module = "com.google.guava:guava", version.ref = "com-google-guava-guava" }
junit = { module = "junit:junit", version.ref = "junit-junit" }
jna = { module = "net.java.dev.jna:jna", version.ref = "net-java-dev-jna-jna" }
ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
kotlin-compilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "gradlePlugin-dokka" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "gradlePlugin-intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "gradlePlugin-ktfmt" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradlePlugin-nexusPublish" }
shadowJar = { id = "com.gradleup.shadow", version.ref = "gradlePlugin-shadowJar" }
